from __future__ import annotations

from .base import ChartSpec, register_chart_spec


BUILTIN_CHART_SPECS = (
    ChartSpec(
        name="area",
        helper_name="area_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue"),
        sql_strategy="aggregate",
        description="Filled area chart for trends over an ordered x-axis.",
    ),
    ChartSpec(
        name="bar",
        helper_name="bar_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue"),
        sql_strategy="aggregate",
        description="Bar chart for grouped category comparisons.",
    ),
    ChartSpec(
        name="box",
        helper_name="box_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue"),
        sql_strategy="raw",
        description="Box plot showing distribution and outliers.",
    ),
    ChartSpec(
        name="heatmap",
        helper_name="heatmap",
        required_args=(),
        optional_args=("title",),
        sql_strategy="derived",
        description="Correlation heatmap of numeric columns.",
    ),
    ChartSpec(
        name="histogram",
        helper_name="histogram",
        required_args=("column",),
        optional_args=("title", "bins", "hue"),
        sql_strategy="raw",
        description="Histogram for a numeric column, optionally split by hue.",
    ),
    ChartSpec(
        name="line",
        helper_name="line_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue"),
        sql_strategy="aggregate",
        description="Line chart for ordered trends or time series.",
    ),
    ChartSpec(
        name="pie",
        helper_name="pie_chart",
        required_args=("labels", "values"),
        optional_args=("title",),
        sql_strategy="aggregate",
        description="Pie or donut chart for category shares.",
    ),
    ChartSpec(
        name="scatter",
        helper_name="scatter_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue", "size"),
        sql_strategy="raw",
        description="Scatter plot for relationships between raw columns.",
    ),
    ChartSpec(
        name="violin",
        helper_name="violin_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue"),
        sql_strategy="raw",
        description="Violin plot for richer distribution views.",
    ),
    ChartSpec(
        name="count",
        helper_name="count_chart",
        required_args=("x",),
        optional_args=("title", "hue"),
        sql_strategy="raw",
        description="Count/frequency bar chart for categorical columns.",
    ),
    ChartSpec(
        name="kde",
        helper_name="kde_chart",
        required_args=("column",),
        optional_args=("title", "hue"),
        sql_strategy="raw",
        description="Kernel density estimate (KDE) plot for continuous distributions.",
    ),
    ChartSpec(
        name="strip",
        helper_name="strip_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue"),
        sql_strategy="raw",
        description="Strip plot showing individual data points per category.",
    ),
    ChartSpec(
        name="regression",
        helper_name="regression_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue"),
        sql_strategy="raw",
        description="Scatter plot with linear regression trend line and confidence band.",
    ),
    ChartSpec(
        name="pairplot",
        helper_name="pairplot_chart",
        required_args=(),
        optional_args=("title", "hue", "columns"),
        sql_strategy="raw",
        description="Scatter matrix across all (or selected) numeric columns.",
    ),
    ChartSpec(
        name="stacked_bar",
        helper_name="stacked_bar_chart",
        required_args=("x", "y", "stack"),
        optional_args=("title", "normalize"),
        sql_strategy="aggregate",
        description="Stacked (or 100%-normalised) bar chart showing part-to-whole across categories.",
    ),
    ChartSpec(
        name="bubble",
        helper_name="bubble_chart",
        required_args=("x", "y", "size"),
        optional_args=("title", "hue"),
        sql_strategy="raw",
        description="Bubble chart — scatter with a third numeric dimension encoded as marker size.",
    ),
    ChartSpec(
        name="step",
        helper_name="step_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue"),
        sql_strategy="aggregate",
        description="Step/staircase line chart for discrete-interval or cumulative data.",
    ),
    ChartSpec(
        name="swarm",
        helper_name="swarm_chart",
        required_args=("x", "y"),
        optional_args=("title", "hue"),
        sql_strategy="raw",
        description="Swarm/beeswarm plot — non-overlapping jittered points per category.",
    ),
    ChartSpec(
        name="ecdf",
        helper_name="ecdf_chart",
        required_args=("column",),
        optional_args=("title", "hue"),
        sql_strategy="raw",
        description="Empirical cumulative distribution function (ECDF) plot.",
    ),
    ChartSpec(
        name="funnel",
        helper_name="funnel_chart",
        required_args=("labels", "values"),
        optional_args=("title",),
        sql_strategy="aggregate",
        description="Funnel chart showing sequential stage-by-stage drop-off.",
    ),
)

BUILTIN_CHART_TYPES = tuple(spec.name for spec in BUILTIN_CHART_SPECS)

for spec in BUILTIN_CHART_SPECS:
    register_chart_spec(spec)